# Dockerfile.backend
FROM node:21

# Set working directory
WORKDIR /app

# Copy backend files
COPY . .

# Install dependencies
RUN npm install

# Expose backend port
EXPOSE 3000

# Start backend server
CMD ["npm", "start"]
